#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
namespace: #@ data.values.metallb.namespace
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"metallb-config"}})
---
stringData:
  values.yml: #@ yaml.encode(config())