apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-ctrl
  annotations:
    kapp.k14s.io/change-group.1: "metallb.tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-group.2: "tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-rule.insert: "upsert after upserting tkgdev.failk8s.com/namespace"
    kapp.k14s.io/change-rule.delete: "delete after deleting metallb.tkgdev.failk8s.com/package"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: metallb-ctrl-sa
    namespace: dev-platform-ctrl