#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
#! namespace: #@ data.values.ingress.namespace
#! privileged_clusterrole_name: #@ data.values.privileged_clusterrole_name
envoy:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: #@ "*.{}.,*.{}.".format(data.values.domain, data.values.wildcard_domain)
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"contour"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
