#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if data.values.metallb.ip_range:

#@ def config():
#! namespace: #@ data.values.metallb.namespace
ip_range: #@ data.values.metallb.ip_range
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"metallb"}})
---
stringData:
  values.yml: #@ yaml.encode(config())

#@ else:

#@overlay/match by=overlay.subset({"metadata":{"name":"metallb"}}),expects=4
#@overlay/remove
---

#@ end