#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
#! namespace: #@ data.values.ingress.namespace
#! wildcard:
#!   namespace: #@ data.values.ingress.namespace
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"secretcopier-operator"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
