#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if data.values.certs_use == "aws":

#@ def config():
domain: #@ data.values.domain
provider: aws
aws:
  access_key_id: #@ data.values.aws.access_key_id
  secret_access_key: #@ data.values.aws.secret_access_key
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"external-dns"}})
---
stringData:
  values.yml: #@ yaml.encode(config())

#@ else:

#@overlay/match by=overlay.subset({"metadata":{"name":"external-dns"}}),expects=3
#@overlay/remove
---

#@overlay/match by=overlay.subset({"kind":"ClusterRoleBinding","metadata":{"name":"dev-platform-package:external-dns"}})
#@overlay/remove
---

#@ end