---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "external-dns.tkgdev.failk8s.com/package"
    kapp.k14s.io/change-rule.insert: "upsert after upserting external-dns.tkgdev.failk8s.com/rbac"
spec:
  serviceAccountName: external-dns-ctrl-sa
  packageRef:
    refName: external-dns.tkgdev.failk8s.com
    versionSelection:
      constraints: "0.8.0"
      prereleases: {}
  values:
  - secretRef:
      name: external-dns-config