apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager
  annotations:
    kapp.k14s.io/change-group.1: cert-manager.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting cert-manager.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: cert-manager.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting cert-manager.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: cert-manager.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting cert-manager.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: cert-manager.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting cert-manager.dev.failk8s.com/rbac
spec:
  serviceAccountName: cert-manager
  packageRef:
    refName: cert-manager.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certs
  annotations:
    kapp.k14s.io/change-group.1: certs.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting certs.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: certs
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certs
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: certs.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting certs.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: certs
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: certs.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting certs.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: certs
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: certs.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting certs.dev.failk8s.com/rbac
spec:
  serviceAccountName: certs
  packageRef:
    refName: certs.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: certs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contour
  annotations:
    kapp.k14s.io/change-group.1: contour.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting contour.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: contour
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: contour.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting contour.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: contour
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: contour.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting contour.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: contour.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting contour.dev.failk8s.com/rbac
spec:
  serviceAccountName: contour
  packageRef:
    refName: contour.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: contour
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
  annotations:
    kapp.k14s.io/change-group.1: external-dns.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting external-dns.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: external-dns.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting external-dns.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: external-dns.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting external-dns.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: external-dns.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting external-dns.dev.failk8s.com/rbac
spec:
  serviceAccountName: external-dns
  packageRef:
    refName: external-dns.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving
  annotations:
    kapp.k14s.io/change-group.1: knative-serving.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting knative-serving.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: knative-serving
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-serving
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: knative-serving.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting knative-serving.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: knative-serving.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting knative-serving.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative-serving
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: knative-serving.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting knative-serving.dev.failk8s.com/rbac
spec:
  serviceAccountName: knative-serving
  packageRef:
    refName: knative-serving.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: knative-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb
  annotations:
    kapp.k14s.io/change-group.1: metallb.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting metallb.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: metallb
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: metallb.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting metallb.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: metallb
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: metallb.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting metallb.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metallb
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: metallb.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting metallb.dev.failk8s.com/rbac
spec:
  serviceAccountName: metallb
  packageRef:
    refName: metallb.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: metallb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry
  annotations:
    kapp.k14s.io/change-group.1: registry.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting registry.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: registry
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: registry.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting registry.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: registry.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting registry.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: registry
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: registry.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting registry.dev.failk8s.com/rbac
spec:
  serviceAccountName: registry
  packageRef:
    refName: registry.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretcopier-operator
  annotations:
    kapp.k14s.io/change-group.1: secretcopier-operator.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting secretcopier-operator.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: secretcopier-operator
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretcopier-operator
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: secretcopier-operator.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting secretcopier-operator.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: secretcopier-operator
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: secretcopier-operator.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting secretcopier-operator.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: secretcopier-operator
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: secretcopier-operator.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting secretcopier-operator.dev.failk8s.com/rbac
spec:
  serviceAccountName: secretcopier-operator
  packageRef:
    refName: secretcopier-operator.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: secretcopier-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testapp
  annotations:
    kapp.k14s.io/change-group.1: testapp.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting testapp.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: testapp
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: testapp.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting testapp.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: testapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: testapp.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting testapp.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: testapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: testapp.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting testapp.dev.failk8s.com/rbac
spec:
  serviceAccountName: testapp
  packageRef:
    refName: testapp.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: testapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testknativeapp
  annotations:
    kapp.k14s.io/change-group.1: testknativeapp.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting testknativeapp.dev.failk8s.com/package
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: testknativeapp
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testknativeapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group.1: testknativeapp.dev.failk8s.com/rbac
    kapp.k14s.io/change-group.2: dev.failk8s.com/rbac
    kapp.k14s.io/change-rule.insert: upsert after upserting dev.failk8s.com/namespace
    kapp.k14s.io/change-rule.delete: delete after deleting testknativeapp.dev.failk8s.com/package
---
apiVersion: v1
kind: Secret
metadata:
  name: testknativeapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: testknativeapp.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting testknativeapp.dev.failk8s.com/rbac
stringData:
  values.yml: null
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: testknativeapp
  namespace: dev-platform
  annotations:
    kapp.k14s.io/change-group: testknativeapp.dev.failk8s.com/package
    kapp.k14s.io/change-rule.insert: upsert after upserting testknativeapp.dev.failk8s.com/rbac
spec:
  serviceAccountName: testknativeapp
  packageRef:
    refName: testknativeapp.dev.failk8s.com
    versionSelection:
      constraints: 0.0.0+develop
      prereleases: {}
  values:
  - secretRef:
      name: testknativeapp
